default_args = {
    'his_k_length': int(1e5),
    'exp_id': '00002',
    'task': 'traj_loc_pred',
    'downstream': True,
    'pre_model_name': 'LPA',
    'embed_name': 'downstream',
    'activity_type': 'A6',  # "None" "A3" "A6" "L6"
    'dataset': 'data_sample',
    'config_file': None,
    'saved_model': True,
    'train': True,
    'attn_type': 'dot',
    'seed': 0,
    'loc_emb_size': 500,
    'uid_emb_size': 40,
    'tim_emb_size': 10,
    'act_emb_size': 2,
    'hidden_size': 500,
    'rnn_type': 'LSTM',
    'dropout_p': 0.5,
    'learning_rate': 0.001,
    'lr_step': 3,
    'max_epoch': 30,
    'optimizer': 'adam',
    'min_session_len': 2,
    'max_session_len': 5,
    'min_sessions': 2,
    'min_checkins': 3,
    'window_size': 6,
    'batch_size': 20,
    'num_workers': 0,
    'cache_dataset': True,
    'train_rate': 0.7,
    'eval_rate': 0.1,
    'history_type': 'splice',
    'cut_method': 'time_interval',
    'gpu': True,
    'gpu_id': 0,
    'L2': 1e-05,
    'lr_decay': 0.1,
    'clip': 5.0,
    'schedule_threshold': 0.001,
    'loss_func': 'default',
    'load_best_epoch': True,
    'hyper_tune': False,
    'early_stop_lr': 9e-06,
    'debug': False,
    'metrics': ['Precision', 'Recall', 'F1', 'MRR', 'NDCG', 'GeoDis'],
    'evaluate_method': 'popularity',
    'topk': [1, 3, 5, 10],
    'geo': {
        'including_types': ['Point'],
        'Point': {'geo_id': 'geo_id', 'type': 'other', 'coordinate': 'coordinate'}
    },
    'usr': {
        'properties': {'usr_id': 'usr_id'}
    },
    'dyna': {
        'including_types': ['trajectory'],
        'trajectory': {
            'dyna_id': 'num',
            'type': 'other',
            'time': 'time',
            'entity_id': 'usr_id',
            'location': 'geo_id',
            'primary_activity': 'enum',
            'secondary_activity': 'enum',
            'Eating out': 'num',
            'Personal affairs': 'num',
            'Recreation': 'num',
            'Shopping': 'num',
            'Home': 'num',
            'Work': 'num'
        }
    },
}
